### ISSUE TITLE
graphical view of the boundary environment

### ISSUE THREAD

**Issue by Hetitus** [ilia-kats/NRPSDesigner#82]
hey Ilia, 
vom Prinzip her korrekt, aber irgendwas stimmt mit dem output noch nicht oder soll das so sein? (siehe screenshot) 

![screen shot 2015-01-05 at 10 41 08](https://cloud.githubusercontent.com/assets/4712738/5611527/031ad13c-94c8-11e4-9497-5bda62c1c632.png)

**Comment by ilia-kats** [comment]
Bei mir siehts nicht so aus. Browser? Auflösung?

**Comment by Hetitus** [comment]
Safari, 1280 x 800

**Comment by ilia-kats** [comment]
Kannst du es mir Firefox austesten? Das sieht nach einem Bug in BioJS aus

**Comment by Hetitus** [comment]
In firefox siehts schon besser aus - nur die blauen Grenzen machen nicht vollständig Sinn
![screen shot 2015-01-05 at 10 58 58](https://cloud.githubusercontent.com/assets/4712738/5611679/eb315cce-94c9-11e4-85eb-a847575b0a23.png)

**Comment by ilia-kats** [comment]
Deine Auflösung ist zu klein, BioJS erwartet die Breite von dem Feld in 
Zeichen und das hat Nikos irgendwann mal hardcoded... Da muss ich mir 
mal was einfallen lassen

**Comment by Hetitus** [comment]
Lass dir Zeit ;)
![screen shot 2015-01-05 at 11 09 41](https://cloud.githubusercontent.com/assets/4712738/5611794/6bc557a4-94cb-11e4-8635-ae838525332f.png)
